name: Get Workflow Run Link

on:
  workflow_dispatch:
    inputs:
      workflow_name:
        description: 'Enter the name of the workflow'
        required: true

jobs:
  get_workflow_run_link:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v2

      - name: Find Workflow Run
        id: find_workflow_run
        run: |
          workflow_name="${{ github.event.inputs.workflow_name }}"
          workflow_run_data=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/workflows" | jq -r --arg workflow_name "$workflow_name" '.workflows[] | select(.name == $workflow_name)')
          workflow_run_id=$(echo "$workflow_run_data" | jq -r '.id')
          workflow_run_link="https://github.com/${{ github.repository }}/actions/runs/${workflow_run_id}"
          echo "::set-output name=workflow_run_link::${workflow_run_link}"

      - name: Provide Workflow Run Link
        run: |
          echo "Workflow Run Link: ${{ steps.find_workflow_run.outputs.workflow_run_link }}"
